# Generated by Django 5.2.4 on 2025-10-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manga", "0004_remove_page_likes_pagelike"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="title",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
