# Generated by Django 5.2.4 on 2025-11-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manga", "0005_page_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="manga",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="manga_covers/"),
        ),
    ]
