# Generated by Django 5.2.4 on 2025-11-03 07:46

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manga", "0006_manga_cover_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manga",
            name="cover_image",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True, null=True, upload_to="covers/"
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="image",
            field=imagekit.models.fields.ProcessedImageField(upload_to="pages/"),
        ),
    ]
