# Generated by Django 5.2.4 on 2025-08-31 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manga", "0002_alter_manga_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="likes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
