# Generated by Django 5.2.4 on 2025-11-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manga", "0007_alter_manga_cover_image_alter_page_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="manga",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
