# Generated by Django 5.2.4 on 2025-11-16 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manga", "0008_manga_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="likes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(name="PageLike",),
    ]
